controller_list:
 - name: wheel_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - back_left_wheel_joint
     - back_right_wheel_joint
     - front_left_wheel_joint
     - front_right_wheel_joint
 # - name: hand_controller
 #   action_ns: gripper_action
 #   type: GripperCommand
 #   default: true
 #   parallel: true
 #   joints:
 #     - panda_finger_joint1
 #     - panda_finger_joint2
